version: '3.8'
services:
  web:
    image: alpine:latest
    command: sh -c "echo 'Starting...' && sleep 10 && echo 'Ready' && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 1s
      timeout: 1s
      retries: 1

  client:
    image: alpine:latest
    command: echo "Client running"
    depends_on:
      web:
        condition: service_healthy