version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  client:
    build: ./client
    depends_on:
      web:
        condition: service_healthy