steps:
  - label: Timeout test
    command: sleep 120
    timeout_in_minutes: 1
    retry:
      automatic:
        - exit_status: 255
          limit: 0
          signal_reason: cancel
        - exit_status: 255
          limit: 2
          signal_reason: none
        - exit_status: -1
          limit: 0
          signal_reason: cancel
        - exit_status: -1
          limit: 2
          signal_reason: none