steps:
  - command: "false"

notify:
  - slack:
      channels:
        - "#tadhg-test"
      message: "Success!"
    if: build.state == "passed"
  - slack:
      channels:
        - "#tadhg-test"
      message: "fail!"
    if: build.state == "failed"