steps:
  - command: echo 'notification test'

notify:
  - email: "tadhg@buildkite.com"
    if: build.state == "passed"
    message: "build passed"
  - email: "tadhg@buildkite.com"
    if: build.state == "failed"
    message: "build failed"