steps:  
  - label: annotate
    command: echo 'test'
    plugins:
      - bugcrowd/test-summary#v1.8.0:
          inputs:
            - label: rspec
              artifact_path: artifacts/rspec*
              type: junit
          formatter:
            type: details
          context: test-summary