steps:
  - command: echo $MY_SECRET
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          env:
            MY_SECRET: MyTestSecret
      - docker#v1.4.0:
          image: "node:8"
          environment:
            - MY_SECRET
