steps:
  - label: "Verify EC2 startup sudo changes"
    command: |
      # Check the current keepalive value to verify the EC2 startup script ran
      current_keepalive=$(sysctl net.ipv4.tcp_keepalive_time | awk '{print $3}')
      echo "Current keepalive setting: $current_keepalive"
      
      # We expect 7200 since the startup script should have reset to default
      if [ "$current_keepalive" = "7200" ]; then
        echo "✅ EC2 startup script successfully ran and modified sysctl values"
      else
        echo "❌ EC2 startup script may not have run - unexpected keepalive value"
        exit 1
      fi