steps:
  - command: "false"


notify:
  - slack: "@tadhgo"
      message: "success"
    if: build.state == "passed"
  - slack: "tadhg@buildkite.com"
      message: "fail"
    if: build.state == "failed"