steps:
  - label: ':docker: configure image tag'
    key: 'tag:create'
    commands:
      - TAG=$(echo 'test-tag')
      - "echo $TAG"
      - 'buildkite-agent meta-data set "TAG" "\${TAG}"'
      - 'buildkite-agent step update "label" ":sunglasses': 'TAG=\${TAG}"'
