steps:
  - label: ":camera_with_flash:"
    command: "ls -al images/*.png"
    artifact_paths:
      - "./images/*.png"
    key: upload
  - label: ":shipit: Trigger build"
    trigger: "dynamic-pipeline-steps-example"
    depends_on: upload