steps:
  - label: Timeout test
    command: sleep 120
    timeout_in_minutes: 1
    retry:
      automatic:
        - exit_status: 255
          limit: 2
          if: "build.env['BUILDKITE_TIMEOUT'] != 'false'"