steps:
  - label: ":one-does-not-simply: upload dat metadata"
    command: buildkite-agent meta-data set "foo" "bar" 
    key: metadata
  - label: reading log file location
    command: echo '$BUILDKITE_ENABLE_JOB_LOG_TMPFILE'